import React from "react"
import type { Metadata } from "next";
// import { Inter } from "next/font/google";

import Navbar from "@/components/navbar"
import Footer from "@/components/footer"
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Home Page",
   description: "Generated by create next app",
};

function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
   return (
      <html lang="en">
         <body data-theme="dim">
            <Navbar />
            {children}
            <Footer />
         </body>
      </html>
   );
}
export default RootLayout